services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - backend_network
    depends_on:
      - apigateway

  apigateway:
    build:
      context: ../ApiGateway
      dockerfile: Dockerfile
    ports:
      - "4001:4001" 
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge